FROM golang:1.25.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -ldflags="-s -w" \
    -o compiler cmd/compiler/main.go

FROM scratch

COPY --from=builder /app/compiler /compiler

ENTRYPOINT ["/compiler"]